import type { Metadata } from "next";
import { IconQuestionMark } from '@tabler/icons-react';
import { IconUsers } from '@tabler/icons-react';
import { IconBrandAndroid } from '@tabler/icons-react';
import { Geist, Geist_Mono } from "next/font/google";
import   "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <nav className="navbar">
                            <a href="#">
                            <IconBrandAndroid stroke={2} />
                                TaskHub
                            </a>
                            <a href="/contact">
                            <IconUsers stroke={2} />
                                Personal
                            </a>
                            <a href="#">
                            <IconQuestionMark stroke={2} />
                                Undefined
                            </a>
                        </nav>
        {children}
      </body>
    </html>
  );
}
